name: Publish to NPM

on:
  release:
    type: [ created ]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          registry-url: https://registry.npmjs.org/
          
      - name: install packages
        run: npm install
      - name: start tests
        run: npm test
      - name: start publishing
        run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
